title: Avancée des recherches - Michel TARBY
description: Pages en markdown pour organiser le travail effectué en tant qu'IR puis doctorant
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# Options supplémentaires
markdown: kramdown

# Pages à afficher dans le bandeau de navigation
header_pages:
  - index.md
  - page-reunions.md
  - page-recherche.md

