title: Avancée des recherches - Michel TARBY
description: Pages en markdown pour organiser le travail effectué en tant qu'IR puis doctorant
theme: minima

# Options supplémentaires
markdown: kramdown
plugins:
  - jekyll-feed

# Pages à afficher dans le bandeau de navigation
header_pages:
  - index.md
  - page-reunions.md