title: Avancée des recherches - Michel TARBY
description: Pages en markdown pour organiser le travail effectué en tant qu'IR puis doctorant

remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme
# Options supplémentaires
markdown: kramdown

# Pages à afficher dans le bandeau de navigation
header_pages:
  - index.md
  - page-reunions.md
  - page-recherche.md

